import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar/navbar";
import { Footer } from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body>
      <div>
      <Navbar></Navbar>
      <div className=" md:ml-56 md:mr-56">
      {children}
      </div>
      <Footer/>
      </div>
    
      </body>
    </html>
  );
}
